### ISSUE TITLE
Bartender Login Data

### ISSUE THREAD

**Issue by nawwx3** [bmsr56/cs4096#4]
Ok so how this is currently setup is for the bartender to be in separate "tables" like such, where "accounts" is for just regular users

~~~ json
{
    "accounts": { 
             "userId": {
                        "email": "test@me.com"
              },
              "userId": {
                        "email": "test@me.com"
              }
      },
      "bartenders": {
               "userId": {
                        "email": "bartender_email@gmail.com"
              }
      }
}
~~~
So we have bartender and "user" accounts in "tables". 
The problem is that as, as of right now, are __not able to differentiate__ between bartenders and users when making new accounts, __which is when they would be put into these tables__ which effects the table that is loaded on login. 

So do we want to make it so that bartenders have to be added...
- Manually
  - easiest
  - can chalk it up to "hiring/initiation process stuff"
- Automatically
  - harder
  - going to have to make some sort of check
    - also means everyone could do so
- some page from Bartender Activity
  - add new bartenders from behind the scenes

**Comment by RyonOwings** [comment]
I believe that adding bartenders is something that will only occur during the hiring/training process of a business.
That being said, I can imagine that the trainer (a bartender already registered in the system) will have the responsibility of getting the new bartender added onto the system.

Therefore, I personally like the idea of having it be a **page from the Bartender Activity**.
 So with that, my view is that the bartenders will have the responsibility to not access the feature unless the situation calls for it (training, etc).

**Stretch Goal:**
From a product standpoint, I believe it would be useful to have a "Setup" activity like when you first receive a new phone/electronic-device. It would be in this activity where the initial bartender(s) will be added (which will likely be done by the business owner or product purchaser). After the initial bartender(s) are registered during setup, any subsequent bartenders will be added via a page from the Bartender Activity as mentioned above.
